export { api, ApiError, clearToken, getToken, onNoAutorizado, setToken } from './client.js'
export * as auth from './auth.js'
export * as usuarios from './usuarios.js'
export * as clientes from './clientes.js'
export * as vehiculos from './vehiculos.js'
export * as espacios from './espacios.js'
export * as movimientos from './movimientos.js'
export * as tarifas from './tarifas.js'
export * as pagos from './pagos.js'
export * as reservas from './reservas.js'
export * as mensualidades from './mensualidades.js'
export * as alertas from './alertas.js'
export * as turnos from './turnos.js'
export * as panel from './panel.js'
